import type { Pantry } from './types';

// Real font family names (loaded by the player via useFonts / Google), not CSS vars.
const SERIF = 'Fraunces';
const SANS = 'Archivo';

export const SEED_PANTRY: Pantry = {
  backgrounds: [
    {
      id: 'storm-water',
      name: 'Storm water',
      role: 'Opener',
      effectType: 'gradient-background',
      config: { background: 'radial-gradient(900px 540px at 56% 34%,rgba(150,172,196,.34),transparent 64%),linear-gradient(180deg,#1b232c 0%,#0e141a 60%,#0a0e13 100%)', motion: 'breathe', speed: 'slow' },
      mood: ['resolve', 'calm'],
      metaphor: 'A still surface over real depth.',
      motion: ['slow push in', 'drift'],
      zones: 'Center and lower third are dark and safe for type.',
      contrast: 'low',
    },
    {
      id: 'first-light',
      name: 'First light',
      role: 'Closer',
      effectType: 'gradient-background',
      config: { background: 'radial-gradient(880px 560px at 68% 80%,rgba(228,176,120,.40),transparent 66%),linear-gradient(180deg,#191310 0%,#241a14 70%,#15100d 100%)', motion: 'drift', speed: 'slow' },
      mood: ['hope', 'breakthrough'],
      metaphor: 'First light coming up off the water.',
      motion: ['pan up', 'slow push in'],
      zones: 'Upper half holds type best.',
      contrast: 'low',
    },
    {
      id: 'deep-current',
      name: 'Deep current',
      role: 'The turn',
      effectType: 'gradient-background',
      config: { background: 'radial-gradient(920px 620px at 42% 28%,rgba(96,138,190,.38),transparent 64%),linear-gradient(180deg,#0d1822 0%,#0a121c 55%,#070d15 100%)', motion: 'breathe', speed: 'slow' },
      mood: ['introspection', 'struggle'],
      metaphor: 'The weight underneath the calm.',
      motion: ['drift'],
      zones: 'Center only. Edges fall off dark.',
      contrast: 'low',
    },
    {
      id: 'ember',
      name: 'Ember',
      role: 'Climax',
      effectType: 'gradient-background',
      config: { background: 'radial-gradient(760px 520px at 50% 92%,rgba(228,116,72,.46),transparent 64%),linear-gradient(180deg,#1a1310 0%,#241410 65%,#120b09 100%)', motion: 'glow', speed: 'slow' },
      mood: ['intensity', 'drive'],
      metaphor: 'A banked fire about to catch.',
      motion: ['slow push in'],
      zones: 'Upper and center. Keep type off the glow.',
      contrast: 'medium',
    },
    {
      id: 'horizon',
      name: 'Horizon',
      role: 'Opener or closer',
      effectType: 'gradient-background',
      config: { background: 'linear-gradient(180deg,#141c24 0%,#222c36 50%,#0f161d 100%),radial-gradient(1100px 480px at 50% 50%,rgba(180,196,212,.30),transparent 62%)', motion: 'drift', speed: 'slow' },
      mood: ['clarity', 'purpose'],
      metaphor: 'An open line where the sky meets the water.',
      motion: ['pan right', 'push in'],
      zones: 'Center band is clean.',
      contrast: 'low',
    },
    {
      id: 'liquid-light',
      name: 'Liquid light',
      role: 'Opener or climax',
      effectType: 'liquid-gradient',
      config: { backgroundColor: '#080a0f', color1: '#1271ff', color2: '#dd4aff', color3: '#64dcff', color4: '#c83232', color5: '#b4b432', speed: 'slow', blendMode: 'hard-light' },
      mood: ['alive', 'expansive', 'wonder'],
      metaphor: 'Color moving like light through water.',
      motion: ['drift', 'slow swirl'],
      zones: 'Center stays readable; keep type off the brightest orb.',
      contrast: 'medium',
    },
    {
      id: 'open-ocean',
      name: 'Open ocean',
      role: 'Opener',
      effectType: 'ocean',
      config: { elevation: 2, azimuth: 140.2, exposure: 0.0781, distortionScale: 1.3, size: 1, bloomStrength: 0.16, bloomRadius: 1, cloudCoverage: 0, cloudDensity: 0, cloudElevation: 1 },
      mood: ['calm', 'clarity', 'vast'],
      metaphor: 'Real water moving to the horizon.',
      motion: ['drift'],
      zones: 'Center holds type; the horizon is bright.',
      contrast: 'medium',
    },
    {
      id: 'drifting-cloud',
      name: 'Drifting cloud',
      role: 'The turn',
      effectType: 'cloudy-background',
      config: { cloudColor: '#9aa5af', speed: 'slow', opacity: 0.35, layers: 3 },
      mood: ['soft', 'dream', 'calm'],
      metaphor: 'Slow weather passing through.',
      motion: ['drift'],
      zones: 'Center stays readable.',
      contrast: 'low',
    },
  ],
  textEffects: [
    { id: 'reveal-rise', name: 'Reveal rise', effectType: 'masked-text-reveal', config: { splitMode: 'lines', speed: 'slow' }, register: ['tender', 'reflective'], pacing: 'slow', bestFor: ['opening', 'resolution'], needs: 'A high-contrast zone with room to breathe.' },
    { id: 'hard-cut', name: 'Hard cut', effectType: 'hard-cut', config: { speed: 'fast' }, register: ['punchy', 'urgent'], pacing: 'fast', bestFor: ['climax'], needs: 'Strong contrast behind a single line.' },
    { id: 'word-build', name: 'Word build', effectType: 'masked-text-reveal', config: { splitMode: 'words', speed: 'medium' }, register: ['building', 'deliberate'], pacing: 'medium', bestFor: ['the turn'], needs: 'Short lines of three to six words.' },
    { id: 'slow-bloom', name: 'Slow bloom', effectType: 'bloom', config: { speed: 'slow' }, register: ['meditative', 'calm'], pacing: 'slow', bestFor: ['opening'], needs: 'Space and a quiet background.' },
    { id: 'pulse', name: 'Pulse', effectType: 'pulse', config: { speed: 'medium' }, register: ['intense'], pacing: 'medium', bestFor: ['climax'], needs: 'One strong line, nothing competing.' },
    { id: 'dreamy-smoke', name: 'Dreamy smoke', effectType: 'dreamy-smoke', config: { speed: 'slow' }, register: ['dreamy', 'atmospheric', 'soft'], pacing: 'slow', bestFor: ['opening', 'resolution'], needs: 'A quiet backdrop; the line drifts in then smokes away.' },
    { id: 'plain-line', name: 'Plain line', effectType: 'basic-text', config: {}, register: ['plain', 'quiet'], pacing: 'medium', bestFor: ['the turn'], needs: 'When the line should simply sit, no motion.' },
  ],
  pairings: [
    { id: 'p1', bgId: 'storm-water', fxId: 'reveal-rise', text: 'Be one.', attr: '', font: SERIF, cap: 64, color: '#eef3f7', pos: 'center', mood: ['resolve', 'calm'], best: ['opening'] },
    { id: 'p2', bgId: 'horizon', fxId: 'slow-bloom', text: 'Still water.', attr: '', font: SERIF, cap: 72, color: '#eef3f7', pos: 'center', mood: ['clarity', 'calm'], best: ['opening'] },
    { id: 'p3', bgId: 'deep-current', fxId: 'word-build', text: 'The work is the want.', attr: '', font: SERIF, cap: 60, color: '#cfd8df', pos: 'center', mood: ['introspection', 'resolve'], best: ['the turn'] },
    { id: 'p4', bgId: 'ember', fxId: 'hard-cut', text: 'Move now.', attr: '', font: SANS, cap: 64, color: '#eef3f7', pos: 'center', mood: ['intensity', 'drive'], best: ['climax'] },
    { id: 'p5', bgId: 'ember', fxId: 'pulse', text: 'This is the rep.', attr: '', font: SERIF, cap: 62, color: '#eef3f7', pos: 'center', mood: ['intensity'], best: ['climax'] },
    { id: 'p6', bgId: 'first-light', fxId: 'reveal-rise', text: 'Carry it into the day.', attr: '', font: SERIF, cap: 58, color: '#eef3f7', pos: 'upper', mood: ['hope', 'breakthrough'], best: ['resolution'] },
    { id: 'p7', bgId: 'horizon', fxId: 'reveal-rise', text: 'Then you set out.', attr: '', font: SERIF, cap: 64, color: '#eef3f7', pos: 'center', mood: ['clarity', 'purpose'], best: ['resolution'] },
    { id: 'p8', bgId: 'deep-current', fxId: 'dreamy-smoke', text: 'Let it settle.', attr: '', font: SERIF, cap: 66, color: '#eef3f7', pos: 'center', mood: ['introspection', 'calm'], best: ['opening', 'the turn'] },
    { id: 'p9', bgId: 'open-ocean', fxId: 'reveal-rise', text: 'Set your line.', attr: '', font: SERIF, cap: 60, color: '#eef3f7', pos: 'center', mood: ['clarity', 'calm'], best: ['opening'] },
  ],
  rules: [
    'Arrive calm. Leave charged.',
    'Match motion energy to the weight of the line.',
    'Change the backdrop only when the meaning actually shifts.',
    'Give the hero line its own beat with room around it.',
    'Never drop a soft effect on a soft zone.',
    'Let the message decide how many beats, not a template.',
  ],
};

export const SEED_TASTE = {
  arc: 'calm-charged' as const,
  maxBeats: 4,
  backdrop: 'shift' as const,
  quotesReflective: true,
};

export const QUOTES = [
  { text: 'Waste no more time arguing about what a good person should be. Be one.', attr: 'Marcus Aurelius' },
  { text: 'We are what we repeatedly do. Excellence, then, is not an act but a habit.', attr: 'Aristotle' },
  { text: 'The impediment to action advances action. What stands in the way becomes the way.', attr: 'Marcus Aurelius' },
];

export const LINES: Record<string, string[]> = {
  opener: ['Still water.', 'Begin before you feel ready.', 'The day is already yours.', 'Be one.'],
  turn: ['The work is the want.', 'Small and certain beats big and someday.', 'You have done hard things before.'],
  climax: ['Then you set out.', 'Move now, feel it later.', 'This is the rep that counts.'],
  closer: ['Every rep is a vote for who you become.', 'Show up before the world wakes.', 'Carry it into the day.'],
};
